namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class Ation
		{
			[JsonProperty("system")]
			public string System { get; set; }

			[JsonProperty("place")]
			public string Place { get; set; }

			[JsonProperty("setup")]
			public string Setup { get; set; }

			[JsonProperty("x")]
			public long X { get; set; }

			[JsonProperty("y")]
			public long Y { get; set; }
		}
	}
}
