namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class BoostWindow
		{
			[JsonProperty("window")]
			public List<long> Window { get; set; }

			[JsonProperty("reward")]
			public VideoAdChronitonBoostRewardClass Reward { get; set; }
		}
	}
}
