namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class CadetSchedule
		{
			[JsonProperty("day")]
			public long Day { get; set; }

			[JsonProperty("schedule")]
			public List<Schedule> Schedule { get; set; }

			[JsonProperty("missions")]
			public List<Mission> Missions { get; set; }

			[JsonProperty("current")]
			public long Current { get; set; }

			[JsonProperty("ends_in")]
			public double EndsIn { get; set; }

			[JsonProperty("next")]
			public long Next { get; set; }

			[JsonProperty("next_starts_in")]
			public double NextStartsIn { get; set; }
		}
	}
}
