namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System;

		public partial class ClaimedHistory
		{
			[JsonProperty("what")]
			public FromEnum What { get; set; }

			[JsonProperty("when")]
			public DateTimeOffset When { get; set; }

			[JsonProperty("to", NullValueHandling = NullValueHandling.Ignore)]
			public FromEnum? To { get; set; }

			[JsonProperty("from", NullValueHandling = NullValueHandling.Ignore)]
			public FromEnum? From { get; set; }

			[JsonProperty("quantity", NullValueHandling = NullValueHandling.Ignore)]
			[JsonConverter(typeof(ParseStringConverter))]
			public long? Quantity { get; set; }

			[JsonProperty("who", NullValueHandling = NullValueHandling.Ignore)]
			public string Who { get; set; }

			[JsonProperty("image", NullValueHandling = NullValueHandling.Ignore)]
			public string Image { get; set; }

			[JsonProperty("ecount", NullValueHandling = NullValueHandling.Ignore)]
			[JsonConverter(typeof(ParseStringConverter))]
			public long? Ecount { get; set; }

			[JsonProperty("reward_image", NullValueHandling = NullValueHandling.Ignore)]
			public string RewardImage { get; set; }

			[JsonProperty("obtain", NullValueHandling = NullValueHandling.Ignore)]
			[JsonConverter(typeof(ParseStringConverter))]
			public long? Obtain { get; set; }
		}
	}
}
