namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System;

		public partial class CommunityLinkImage
		{
			[JsonProperty("file")]
			public Uri File { get; set; }

			[JsonProperty("url")]
			public Uri Url { get; set; }

			[JsonProperty("version")]
			[JsonConverter(typeof(ParseStringConverter))]
			public long Version { get; set; }
		}
	}
}
