namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System;

		public partial class CommunityLink
		{
			[JsonProperty("symbol")]
			public string Symbol { get; set; }

			[JsonProperty("image")]
			public CommunityLinkImage Image { get; set; }

			[JsonProperty("title")]
			public string Title { get; set; }

			[JsonProperty("date")]
			public string Date { get; set; }

			[JsonProperty("url")]
			public Uri Url { get; set; }
		}
	}
}
