namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using Newtonsoft.Json.Converters;
		using System.Globalization;

		//public partial class Welcome
		//{
		//	public static Welcome FromJson(string json)
		//	{
		//		return JsonConvert.DeserializeObject<Welcome>(json, SttUser.Converter.Settings);
		//	}
		//}

		//public static class Serialize
		//{
		//	public static string ToJson(this Welcome self)
		//	{
		//		return JsonConvert.SerializeObject(self, SttUser.Converter.Settings);
		//	}
		//}

		internal static class Converter
		{
			public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
			{
				MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
				DateParseHandling = DateParseHandling.None,
				Converters =
			{
				SkillElementConverter.Singleton,
				FullNameEnumConverter.Singleton,
				AtlasInfoConverter.Singleton,
				VideoAdChronitonBoostRewardSymbolConverter.Singleton,
				OperatorConverter.Singleton,
				SourceConverter.Singleton,
				PurpleNameConverter.Singleton,
				TutorialStateConverter.Singleton,
				FromEnumConverter.Singleton,
				ReasonConverter.Singleton,
				SpecializedConverter.Singleton,
				GrantedSymbolConverter.Singleton,
				new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
			},
			};
		}
	}
}
