namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class CrewAvatar
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("symbol")]
			public string Symbol { get; set; }

			[JsonProperty("name")]
			public string Name { get; set; }

			[JsonProperty("traits")]
			public List<string> Traits { get; set; }

			[JsonProperty("traits_hidden")]
			public List<string> TraitsHidden { get; set; }

			[JsonProperty("short_name")]
			public string ShortName { get; set; }

			[JsonProperty("max_rarity")]
			public long MaxRarity { get; set; }

			[JsonProperty("icon")]
			public IconClass Icon { get; set; }

			[JsonProperty("portrait")]
			public IconClass Portrait { get; set; }

			[JsonProperty("full_body")]
			public IconClass FullBody { get; set; }

			[JsonProperty("default_avatar")]
			public bool DefaultAvatar { get; set; }

			[JsonProperty("hide_from_cryo")]
			public bool HideFromCryo { get; set; }

			[JsonProperty("skills")]
			public List<SkillElement> Skills { get; set; }
		}
	}
}
