namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class CryoCollectionMilestone
		{
			[JsonProperty("rewards")]
			public List<MilestoneReward> Rewards { get; set; }

			[JsonProperty("goal")]
			public long Goal { get; set; }

			[JsonProperty("buffs")]
			public List<ShuttleTokenPreviewItem> Buffs { get; set; }
		}
	}
}
