namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class CurrencyExchange
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("amount")]
			public long Amount { get; set; }

			[JsonProperty("output")]
			public long Output { get; set; }

			[JsonProperty("input")]
			public long Input { get; set; }

			[JsonProperty("schedule")]
			public List<long> Schedule { get; set; }

			[JsonProperty("exchanges_today")]
			public long ExchangesToday { get; set; }

			[JsonProperty("bonus", NullValueHandling = NullValueHandling.Ignore)]
			public long? Bonus { get; set; }

			[JsonProperty("limit", NullValueHandling = NullValueHandling.Ignore)]
			public long? Limit { get; set; }
		}
	}
}
