namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class Demand
		{
			[JsonProperty("archetype_id")]
			public long ArchetypeId { get; set; }

			[JsonProperty("count")]
			public long Count { get; set; }
		}
	}
}
