namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Entitlements
		{
			[JsonProperty("granted")]
			public List<Granted> Granted { get; set; }

			[JsonProperty("claimed")]
			public List<Claimed> Claimed { get; set; }
		}
	}
}
