namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Faction
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("name")]
			public string Name { get; set; }

			[JsonProperty("reputation")]
			public long Reputation { get; set; }

			[JsonProperty("discovered")]
			public long Discovered { get; set; }

			[JsonProperty("completed_shuttle_adventures")]
			public long CompletedShuttleAdventures { get; set; }

			[JsonProperty("icon")]
			public IconClass Icon { get; set; }

			[JsonProperty("representative_icon")]
			public IconClass RepresentativeIcon { get; set; }

			[JsonProperty("representative_full_body")]
			public IconClass RepresentativeFullBody { get; set; }

			[JsonProperty("reputation_icon")]
			public IconClass ReputationIcon { get; set; }

			[JsonProperty("reputation_item_icon")]
			public IconClass ReputationItemIcon { get; set; }

			[JsonProperty("home_system")]
			public string HomeSystem { get; set; }

			[JsonProperty("shop_layout")]
			public string ShopLayout { get; set; }

			[JsonProperty("shuttle_token_id")]
			public long ShuttleTokenId { get; set; }

			[JsonProperty("shuttle_token_preview_item")]
			public ShuttleTokenPreviewItem ShuttleTokenPreviewItem { get; set; }

			[JsonProperty("event_winner_rewards")]
			public List<object> EventWinnerRewards { get; set; }

			[JsonProperty("shuttle_mission_rewards")]
			public List<ShuttleMissionReward> ShuttleMissionRewards { get; set; }
		}
	}
}
