namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		public enum FromEnum { Claimed, Granted, MemberJoinSuccessAfterInviteGidSome1047137872764935, MemberJoinSuccessAfterInviteGidSome888574811693058, Reverted };
	}
}
