namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		public enum FullNameEnum { AdvancedReplicatorRation, DynamicReplicatorRation, Chronitons, Dilithium, FederationCredits, Honor, Merits, PremiumTimePortal, PremiumTimePortal10x, TheNiners, InterstellarMedium };
	}
}
