namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Granted
		{
			[JsonProperty("uuid")]
			public string Uuid { get; set; }

			[JsonProperty("gamerTag")]
			public long GamerTag { get; set; }

			[JsonProperty("symbol")]
			public GrantedSymbol Symbol { get; set; }

			[JsonProperty("state")]
			public FromEnum State { get; set; }

			[JsonProperty("updated")]
			public long Updated { get; set; }

			[JsonProperty("history")]
			public List<GrantedHistory> History { get; set; }

			[JsonProperty("specialized", NullValueHandling = NullValueHandling.Ignore)]
			public Specialized? Specialized { get; set; }
		}
	}
}
