namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class Icon
		{
			[JsonProperty("file")]
			public string File { get; set; }

			[JsonProperty("atlas_info", NullValueHandling = NullValueHandling.Ignore)]
			public AtlasInfo? AtlasInfo { get; set; }
		}
	}
}
