namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class ItemArchetypeCache
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("archetypes")]
			public List<Archetype> Archetypes { get; set; }
		}
	}
}
