namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class MasterLimit
		{
			[JsonProperty("chance")]
			public long Chance { get; set; }

			[JsonProperty("period_minutes")]
			public long PeriodMinutes { get; set; }
		}
	}
}
