namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class Mission
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("title")]
			public string Title { get; set; }

			[JsonProperty("speaker")]
			public string Speaker { get; set; }

			[JsonProperty("description")]
			public string Description { get; set; }

			[JsonProperty("portrait")]
			public IconClass Portrait { get; set; }

			[JsonProperty("image")]
			public IconClass Image { get; set; }

			[JsonProperty("image_small")]
			public IconClass ImageSmall { get; set; }

			[JsonProperty("requirement")]
			public string Requirement { get; set; }
		}
	}
}
