namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Motd
		{
			[JsonProperty("title")]
			public string Title { get; set; }

			[JsonProperty("text")]
			public string Text { get; set; }

			[JsonProperty("priority")]
			public long Priority { get; set; }

			[JsonProperty("image")]
			public IconClass Image { get; set; }

			[JsonProperty("url")]
			public object Url { get; set; }

			[JsonProperty("additional_motds")]
			public List<object> AdditionalMotds { get; set; }
		}
	}
}
