namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Navmap
		{
			[JsonProperty("places")]
			public List<Place> Places { get; set; }

			[JsonProperty("systems")]
			public List<SystemElement> Systems { get; set; }
		}
	}
}
