namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class NextCrewLimitIncreaseCost
		{
			[JsonProperty("currency")]
			public long Currency { get; set; }

			[JsonProperty("amount")]
			public long Amount { get; set; }
		}
	}
}
