namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Player
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("dbid")]
			public long Dbid { get; set; }

			[JsonProperty("lang")]
			public string Lang { get; set; }

			[JsonProperty("timezone")]
			public string Timezone { get; set; }

			[JsonProperty("locale")]
			public string Locale { get; set; }

			[JsonProperty("display_name")]
			public string DisplayName { get; set; }

			[JsonProperty("money")]
			public long Money { get; set; }

			[JsonProperty("premium_purchasable")]
			public long PremiumPurchasable { get; set; }

			[JsonProperty("premium_earnable")]
			public long PremiumEarnable { get; set; }

			[JsonProperty("honor")]
			public long Honor { get; set; }

			[JsonProperty("shuttle_rental_tokens")]
			public long ShuttleRentalTokens { get; set; }

			[JsonProperty("vip_points")]
			public long VipPoints { get; set; }

			[JsonProperty("vip_level")]
			public long VipLevel { get; set; }

			[JsonProperty("currency_exchanges")]
			public List<CurrencyExchange> CurrencyExchanges { get; set; }

			[JsonProperty("replicator_uses_today")]
			public long ReplicatorUsesToday { get; set; }

			[JsonProperty("replicator_limit")]
			public long ReplicatorLimit { get; set; }

			[JsonProperty("character")]
			public Character Character { get; set; }

			[JsonProperty("fleet")]
			public Fleet Fleet { get; set; }

			[JsonProperty("squad")]
			public Squad Squad { get; set; }

			[JsonProperty("mailbox")]
			public Mailbox Mailbox { get; set; }

			[JsonProperty("fleet_invite")]
			public FleetInvite FleetInvite { get; set; }

			[JsonProperty("entitlements")]
			public Entitlements Entitlements { get; set; }

			[JsonProperty("chats")]
			public Chats Chats { get; set; }

			[JsonProperty("commerce")]
			public Chats Commerce { get; set; }

			[JsonProperty("environment")]
			public Environment Environment { get; set; }

			[JsonProperty("motd")]
			public Motd Motd { get; set; }

			[JsonProperty("npe_complete")]
			public bool NpeComplete { get; set; }

			[JsonProperty("community_links")]
			public List<CommunityLink> CommunityLinks { get; set; }
		}
	}
}
