namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		public enum PurpleName { Chronitons, Credits, Dilithium, Honor, Merits, Portal, Portal10x, ReplicatorFuel, TheNiners, ISM };
	}
}
