namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class PvpTimer
		{
			[JsonProperty("supports_rewarding")]
			public bool SupportsRewarding { get; set; }

			[JsonProperty("pvp_allowed")]
			public bool PvpAllowed { get; set; }

			[JsonProperty("changes_in")]
			public double ChangesIn { get; set; }
		}
	}
}
