namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Recipe
		{
			[JsonProperty("demands")]
			public List<Demand> Demands { get; set; }

			[JsonProperty("validity_hash")]
			public string ValidityHash { get; set; }
		}
	}
}
