namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class RerollDescription
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("jackpot")]
			public long Jackpot { get; set; }

			[JsonProperty("crew_required")]
			public long CrewRequired { get; set; }
		}
	}
}
