namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class RewardSkills
		{
			[JsonProperty("diplomacy_skill")]
			public Skill DiplomacySkill { get; set; }

			[JsonProperty("command_skill", NullValueHandling = NullValueHandling.Ignore)]
			public Skill CommandSkill { get; set; }

			[JsonProperty("security_skill", NullValueHandling = NullValueHandling.Ignore)]
			public Skill SecuritySkill { get; set; }
		}
	}
}
