namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class RewardDay
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("symbol")]
			public string Symbol { get; set; }

			[JsonProperty("rewards")]
			public List<RewardDayReward> Rewards { get; set; }

			[JsonProperty("double_at_vip", NullValueHandling = NullValueHandling.Ignore)]
			public long? DoubleAtVip { get; set; }
		}
	}
}
