namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public static class Serialize
		{
			public static string ToJson(this Welcome self)
			{
				return JsonConvert.SerializeObject(self, SttUser.Converter.Settings);
			}
		}
	}
}
