namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Setup
		{
			[JsonProperty("ship_id")]
			public long ShipId { get; set; }

			[JsonProperty("slots")]
			public List<long> Slots { get; set; }
		}
	}
}
