namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class ShuttleAdventure
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("symbol")]
			public string Symbol { get; set; }

			[JsonProperty("name")]
			public string Name { get; set; }

			[JsonProperty("faction_id")]
			public long FactionId { get; set; }

			[JsonProperty("token_archetype_id")]
			public object TokenArchetypeId { get; set; }

			[JsonProperty("challenge_rating")]
			public long ChallengeRating { get; set; }

			[JsonProperty("shuttles")]
			public List<Shuttle> Shuttles { get; set; }

			[JsonProperty("completes_in_seconds")]
			public long CompletesInSeconds { get; set; }

			[JsonProperty("x")]
			public long X { get; set; }

			[JsonProperty("y")]
			public long Y { get; set; }
		}
	}
}
