namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Shuttle
		{
			[JsonProperty("id")]
			public long Id { get; set; }

			[JsonProperty("name")]
			public string Name { get; set; }

			[JsonProperty("description")]
			public string Description { get; set; }

			[JsonProperty("state")]
			public long State { get; set; }

			[JsonProperty("expires_in")]
			public double ExpiresIn { get; set; }

			[JsonProperty("faction_id")]
			public long FactionId { get; set; }

			[JsonProperty("slots")]
			public List<Slot> Slots { get; set; }

			[JsonProperty("rewards")]
			public List<ShuttleTokenPreviewItem> Rewards { get; set; }

			[JsonProperty("is_rental")]
			public bool IsRental { get; set; }
		}
	}
}
