namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class ShuttleMissionReward
		{
			[JsonProperty("type")]
			public long Type { get; set; }

			[JsonProperty("icon")]
			public IconClass Icon { get; set; }

			[JsonProperty("rarity", NullValueHandling = NullValueHandling.Ignore)]
			public long? Rarity { get; set; }

			[JsonProperty("potential_rewards", NullValueHandling = NullValueHandling.Ignore)]
			public List<ShuttleTokenPreviewItem> PotentialRewards { get; set; }

			[JsonProperty("quantity")]
			public long Quantity { get; set; }

			[JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
			public long? Id { get; set; }

			[JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
			public string Name { get; set; }
		}
	}
}
