namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class Slot
		{
			[JsonProperty("level")]
			public object Level { get; set; }

			[JsonProperty("required_trait")]
			public object RequiredTrait { get; set; }

			[JsonProperty("skills")]
			public List<string> Skills { get; set; }

			[JsonProperty("trait_bonuses")]
			public Chats TraitBonuses { get; set; }
		}
	}
}
