namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		public enum Specialized { Premium10XBundle, Premium1XBundle, MinorConsumables10XBundle, PremiumConsumables10XBundle, Standard10XBundle, StandardConsumables10XBundle, StimpackBundle, Standard1XBundle };
	}
}
