namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class Summary
		{
			[JsonProperty("name")]
			public string Name { get; set; }

			[JsonProperty("min")]
			public long Min { get; set; }

			[JsonProperty("max")]
			public long Max { get; set; }
		}
	}
}
