namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class Tickets
		{
			[JsonProperty("current")]
			public long Current { get; set; }

			[JsonProperty("max")]
			public long Max { get; set; }

			[JsonProperty("spend_in")]
			public double SpendIn { get; set; }

			[JsonProperty("reset_in")]
			public double ResetIn { get; set; }
		}
	}
}
