namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		public enum VideoAdChronitonBoostRewardSymbol { Energy, Honor, Nonpremium, Premium1XBundle, Premium10XBundle, PremiumEarnable, PremiumPurchasable, ReplicatorFuelSuperrare, ReplicatorFuelLegendary, NinersAvatar };
	}
}
