namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;
		using System.Collections.Generic;

		public partial class VoyageSummaries
		{
			[JsonProperty("summaries")]
			public List<Summary> Summaries { get; set; }

			[JsonProperty("flavor_amount")]
			public long FlavorAmount { get; set; }
		}
	}
}
