namespace STTDataAnalyzer
{

	// <auto-generated />
	//
	// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
	//
	//    using SttUser;
	//
	//    var welcome = Welcome.FromJson(jsonString);

	namespace SttUser
	{
		using Newtonsoft.Json;

		public partial class VoyageDescriptionSkills
		{
			[JsonProperty("primary_skill")]
			public SkillElement PrimarySkill { get; set; }

			[JsonProperty("secondary_skill")]
			public SkillElement SecondarySkill { get; set; }
		}
	}
}
